### ISSUE TITLE
Breaks angular-loading-bar

### ISSUE THREAD

**Issue by nimrin** [witoldsz/angular-http-auth#107]
Hello. 
I am using angular-loading-bar. A 401 should be considered an error response, otherwise loading spinner never stops.  
Have you any idea how to handle this issue?

**Comment by witoldsz** [comment]
Any reason for closing the issue without any explanation?

**Comment by nimrin** [comment]
I realized that I can use httpBuffer to reject promise when handling 'event:auth-loginRequired' event.

**Comment by nimrin** [comment]
I tried to call httpBuffer.rejectAll() in 'event:auth-loginRequired' handler, but it takes no effect. Question is still actual.

**Comment by nimrin** [comment]
My mistake, I used rejectAll() without any parameter.

**Comment by ronaldheft** [comment]
@nimrin Can you post some sample code for how you fixed this? I'm facing the exact same issue. Are you always calling `httpBuffer.rejectAll()`, or only under certain scenarios?

**Comment by ronaldheft** [comment]
@nimrin Figured it out. The solution is actually much simpler than you described. `authService.loginCancelled()` just needed to be called with a second parameter to provide as the promise rejection.

**Comment by clong365** [comment]
@ronaldheft  would you give me more detail about the solution. I'm still confused now.
