### ISSUE TITLE
doesn't seem to use the config for the next requests

### ISSUE THREAD

**Issue by jarnix** [witoldsz/angular-http-auth#108]
Hello,

I'm trying this code with angular 1.4. The interceptor handles the 401/403 well but seems to add the headers (within the config object) only for the blocked requests, and not for the next ones. The defaults for $http provider are not set.

Am I wrong/tired ?

**Comment by witoldsz** [comment]
What kind of headers? Can you provide a code sample?

**Comment by jarnix** [comment]
Hello,

My app uses an API and the authorization is an additional header, I hade to modify the code to add the addtional header : 

In my login controller, upon a successful login :
```
 AuthInterceptorService.loginConfirmed('success', function(config) {
							config.headers["X-Authorization"] = xAuthorization;
							return config;
						}, xAuthorization);
```

And then in the code of angular-http-auth :

```
loginConfirmed : function(data, configUpdater, authorizationHeader) {
				var updater = configUpdater || function(config) {
					return config;
				};
				$http.defaults.headers.common['X-Authorization'] = authorizationHeader;
				$rootScope.$broadcast('event:auth-loginConfirmed', data);
				HttpBuffer.retryAll(updater);
			},
```

**Comment by witoldsz** [comment]
You have changed this module to suit your specific needs. In your application it might be OK, but in hundreds of other apps currently running this module - it might not be desired behavior.

Maybe it would be better to let your requirement happen in another interceptor?

**Comment by hoppler** [comment]
Hi,

im using http-auth with token too. 
Heres my implementation for adding the token into the header:

```js
angular.module('app.common.identity').factory('authHttpInterceptor', function ($rootScope, identityService) {
    "use strict";
    return {
        'request': function (config) {
            config.headers = config.headers || {};

            var tmpCurrentUser = identityService.getCurrentUser();
            if (tmpCurrentUser) {
                config.headers.Authorization = 'Bearer ' + tmpCurrentUser.token;
            }
            return config;
        }
    };
});
```
