### ISSUE TITLE
bower install warning

### ISSUE THREAD

**Issue by genuinefafa** [witoldsz/angular-http-auth#111]
I just did a bower install (as instructed on the README.md) and it is complaining for something I don't really understand... Maybe there is a missing declaration in the `json`

```
$ bower install --save angular-http-auth
bower angular-http-auth#*   not-cached git://github.com/witoldsz/angular-http-auth.git#*
bower angular-http-auth#*      resolve git://github.com/witoldsz/angular-http-auth.git#*
bower angular-http-auth#*     download https://github.com/witoldsz/angular-http-auth/archive/v1.2.2.tar.gz
bower angular-http-auth#*      extract archive.tar.gz
bower angular-http-auth#*     mismatch Version declared in the json (1.2.1) is different than the resolved one (1.2.2)
bower angular-http-auth#* invalid-meta angular-http-auth is missing "ignore" entry in bower.json
bower angular-http-auth#*     resolved git://github.com/witoldsz/angular-http-auth.git#1.2.2
bower angular-http-auth#~1.2.2 install angular-http-auth#1.2.2
```

**Comment by raoel** [comment]
+1

**Comment by Boboss74** [comment]
+1

**Comment by Boboss74** [comment]
bower.json declared version 1.2.1 in the git branch tagged v1.2.2
https://github.com/witoldsz/angular-http-auth/blob/v1.2.2/bower.json

**Comment by simison** [comment]
@Boboss74 Bower ignores `version` as deprecated and relies only to git tags (https://github.com/bower/spec/blob/master/json.md#version).

The package is missing `ignore` https://github.com/bower/spec/blob/master/json.md#ignore

**Comment by Boboss74** [comment]
In the branch 1.2.2, there is still a  version declared in the bower.json and still missing ignore entry.

So, still having on bower install

    bower angular-http-auth#~1.2.2       mismatch Version declared in the json (1.2.1) is different than the resolved one (1.2.2)
    bower angular-http-auth#~1.2.2   invalid-meta angular-http-auth is missing "ignore" entry in bower.json

**Comment by simison** [comment]
@Boboss74 Yes, these will go in with the next version bump.

**Comment by Boboss74** [comment]
Ok thanks
