### ISSUE TITLE
There is no minified version on bower/npm 

### ISSUE THREAD

**Issue by Mistrall** [witoldsz/angular-http-auth#112]
Can you also add minified version to bower?

**Comment by vlapo** [comment]
+1

**Comment by witoldsz** [comment]
I don't have a build script yet. I suppose I will add one some day. On the other hand, every project I saw either had it's own minification procedure for everything, or they did not care, because it was internal project.

**Comment by simison** [comment]
https://github.com/bower/spec/blob/master/json.md#main

>Do not include minified files.

http://stackoverflow.com/questions/24852850/why-is-bower-recommending-to-ignore-minified-source-file


:-)

**Comment by DaAwesomeP** [comment]
@Mistrall I understand why you would want a minified version, but you really ought to be using your own build script. I would recommend [`generator-gulp-angular`](https://github.com/Swiip/generator-gulp-angular) or [`generator-angular`](https://github.com/yeoman/generator-angular).

**Comment by gitarno** [comment]
The minify version a file is created for easing the life the developer. :+1: 

For default, using Bower.json do download packages library Front-end for motif and NPM do download packages builders and tasks, facilitates management.
