### ISSUE TITLE
login address returns 404 after 401 intercept

### ISSUE THREAD

**Issue by wallstudios** [witoldsz/angular-http-auth#115]
I have another odd one. If I call a page that requires authentication http-auth intercepts it correctly and it calls my login modal. 
When I submit my details I get a 404 from the server but if I click "login" the second time it works as expected.

If I go directly to the login it works every time. 

Would my original 401 be adding something to the headers that is causing my issue?

thanks.

**Comment by witoldsz** [comment]
There is no way anyone here could possibly guess. You have to debug it, just look what exactly goes through the wire.

**Comment by witoldsz** [comment]
Please reopen if you have some new data.
