### ISSUE TITLE
Basic authentication results in 404

### ISSUE THREAD

**Issue by thelamborghinistory** [witoldsz/angular-http-auth#132]
I am quite surprised there is so little issues on this, but how can I login into a Basic authentication like e.g. being generated by an .htaccess / .htpasswd? I am getting a 404 if I try to $http.post() the user to the root of my auth secured app.

**Comment by witoldsz** [comment]
Hi,
this project is not about how you actually login your users to the backend server, it's all about how to deal with authentication HTTP status responses.

**Comment by maximsko** [comment]
It's a concrete use case, and this project lacks examples and documentation in that subject imho. All in all I have the feeling that this library only attracts people who already know pretty much about all the http packet things, I didn't even realize the first time I came across that this was what I needed, until I built up a bunch of more knowledge and some article or SO answer directed me here again.
And even though I think I have some deeper understanding about HTTP requests and responses by now I still didn't manage to make this work with a basic http auth.

**Comment by witoldsz** [comment]
Hi again,
thanks for your feedback. You are probably right, this project is about authentication, and examples, tutorials and descriptions about different use cases could be helpful. 

Note that this is an open project, created by me (and of course the community) for the community. Nobody tries to sell you a product here. We are taking our time to support this initiative, so can you! 

Do your research, write it down and share with us. Find a solution, blog about it, publish the article, create a pull request or let me know, so I could link to it, let others know so they can hear about your research and this project... I don't know what else to say. Just do something about it! It's your move, it's your time! :-)

**Comment by maximsko** [comment]
I really appreciate yours and everyones else time spent on this and other various projects. So thank you for your effort so much!
I am really sorry if my answer sounded ignorant, that wasn't intended. All I was trying to say is, that even if this, or to generalize my statement, any project out there is all about something specific, it is still a valid point to consider and connect the use cases of that specific purpose in one or another way to the project.
Anyhow, if I manage to achieve something in this case or if I think I accumulated enough good and valid stuff about something, I eventually will contribute that to the project for sure. :)
