### ISSUE TITLE
Scenario with refresh token (e.g. authService.ignoreCurrentRequest())

### ISSUE THREAD

**Issue by djleonskennedy** [witoldsz/angular-http-auth#135]
Hello
I have scenario : 

**access_token** : expires 15 min
**refresh_token** : expires 1 day

1) login -> **"access_token"** and **"refresh_token"**
2) after 15 min **"access_token"** expiration date ends and i need to request refresh()

when i call `refresh()` after 1 day, interceptor capture refresh 401 too, and I can't handle `".then(error => error)"`

Is it posible to specify `"authService.ignoreCurrentRequest()"` for example?

Thank you

**Comment by AndriiDidkivsky** [comment]
+

**Comment by witoldsz** [comment]
Yes, ignoring specific requests by this module is possible. See the "Ignoring the 401 interceptor" section of Readme:
https://github.com/witoldsz/angular-http-auth#ignoring-the-401-interceptor

Hope that helps your case.

**Comment by djleonskennedy** [comment]
I need better read doc, it works well, thank you
