### ISSUE TITLE
Please add license = "MIT" to bower.son

### ISSUE THREAD

**Issue by dantran** [witoldsz/angular-http-auth#137]
we have scanner to look for js artifact license, however since the package.json not present, but bower.json is

**Comment by witoldsz** [comment]
The package.json is present and it does contain license: MIT entry.

**Comment by simison** [comment]
@dantran @witoldsz if you install via bower, you get only what's needed for Bower and that [leaves out](https://github.com/witoldsz/angular-http-auth/blob/master/bower.json#L13-L15) package.json

I just went ahead and made a quick PR.
