### ISSUE TITLE
How to revert to previous location after auth-loginCancelled?

### ISSUE THREAD

**Issue by bbshopadmin** [witoldsz/angular-http-auth#55]
When event:auth-loginRequired event is fired on a route change promise, the location has already changed to the new route. How can i revert that location change on the auth-loginCancelled event?

**Comment by sSeewald** [comment]
Hi, I was recently faced with the same problem. My solution is pretty simple:
```
app.run([ '$rootScope', '$location', function ($rootScope,$location) {
    $rootScope.previousLocation = '/';
    $rootScope.currentLocation = '/';
    /** Simply switch the Locations and save the new to current */
    $rootScope.$on("$locationChangeStart", function (e, currentLocation, previousLocation) {
        $rootScope.previousLocation = $rootScope.currentLocation;
        $rootScope.currentLocation = $location.path();
    });
    /** Switch back */
    $rootScope.$on("event:auth-loginCancelled", function (data) {
        $location.path($rootScope.previousLocation);
    });
}]);
```
I hope it helps :)

**Comment by wcyrek-comrise** [comment]
This is useful solution and I may use it.  But I might expend it to something that keeps track of entire history of routes, providing better functionality for a back/forward buttons.  Yes I know browsers can do this, but on mobile I'd prefer to render my own buttons (or rather map it to drag left/right).

**Comment by sSeewald** [comment]
Hi @wcyrek-comrise the history remains intact.

**Comment by witoldsz** [comment]
I think it all goes too far. My experience is that we should never tinker with location on authentication events. This module works best when used as in demo: 
- you do something, 
- then controllers or services ask for data, 
- then server returns 401 (o something else),
- then we just hide (without destroying the DOM content and anything attached to it) the application and show the login dialog (or something else),
- finally we find out the user is now authenticated, so we fire authenticated event and unhide the application,
- it continues where it was blocked by 401 as nothing happened, so the mentioned controllers or services does not even know there was an issue in the meantime.

The only exception to this rule is when the newly logged user is not the same as previously, so we discard all the cached requests and everything and redirect to a landing page.
