### ISSUE TITLE
How to add Token in every request

### ISSUE THREAD

**Issue by farvashani** [witoldsz/angular-http-auth#80]
Dear Friends.
I did my research but i did not find any solution to add the token if it is already exist. 
I know that the updater is supposed to add the token to header after s successful log-in but what about a case when user is already logged in and has a valid token? there should be a function to add the token to any request if the token is available.

is there anything that I am missing here?
I suggest a request function to the interceptors to add the header. is there any similar functionality that i am not aware of?

**Comment by eddiemonge** [comment]
So this can be closed then?
