### ISSUE TITLE
No longer works with 1.3 angular

### ISSUE THREAD

**Issue by GitHubish** [witoldsz/angular-http-auth#81]
I feel that the auth interceptor no longer works with the latest version of angular (1.3)
There has been beaking exchange on $http : API interceptors changed

On my app I can no longer connect . But there is no error in the console.

**Comment by renatomefidf** [comment]
Working here too.

Should this issue still be opened?

**Comment by zoltanradics** [comment]
I think it is no more relevant.

**Comment by witoldsz** [comment]
OK, so I am closing the issue.

**Comment by genuinefafa** [comment]
If it works, then should we update [README.md](https://github.com/witoldsz/angular-http-auth/blob/master/README.md) accordingly?

**Comment by witoldsz** [comment]
@genuinefafa Good idea, I'm waiting forward for a pull request :)
