### ISSUE TITLE
Add loginCancelled to readme file

### ISSUE THREAD

**Issue by david-byng** [witoldsz/angular-http-auth#90]
```
The authService has only one method: #loginConfirmed().
```

```
      loginCancelled: function(data, reason) {
        httpBuffer.rejectAll(reason);
        $rootScope.$broadcast('event:auth-loginCancelled', data);
      }
```

Updating the readme to include info on how to use the loginCancelled method would make it easier for people to get started with angular-http-auth.

**Comment by moskeyombus** [comment]
Finding this issue saved me from pulling `angular-http-auth` out of my project entirely.  PR opened to fix the documentation.
