### ISSUE TITLE
Support for commonJS syntax

### ISSUE THREAD

**Issue by jgoux** [witoldsz/angular-http-auth#92]
Could you consider adding support for commonJS so we can install angular-http-auth with NPM ?
The work is already done in forks like this one : https://github.com/twalling/angular-http-auth

**Comment by witoldsz** [comment]
I'll take a look at it soon.

**Comment by witoldsz** [comment]
The "angular-http-auth" is now available as an npm package. I am not sure about CommonJS though. Is that a one-way ticket? What if someone use RequireJS or yet something else?

**Comment by petermetz** [comment]
@witoldsz There are solutions for supporting multiple module formats, details explained [here](http://stackoverflow.com/questions/13673346/supporting-both-commonjs-and-amd) and [here](https://github.com/umdjs/umd)

Obviously it's a way street in the sense that if you opt to support any module format and later on what to remove the support, then you'll have some people complaining that they are stuck on older versions.

Other than that, I personally don't see any risk in adding support for any of the module formats at all.

**Comment by simison** [comment]
PR: #126

**Comment by witoldsz** [comment]
Merged, released and published to npmjs.org.
