### ISSUE TITLE
Request Buffering

### ISSUE THREAD

**Issue by biblicalph** [witoldsz/angular-http-auth#97]
Great job witoldsz. Just a little addition requested. Can you add an ignoreAuthBuffer config variable? I have added it to the local copy I am using. Very useful for SPAs in which you handler logouts by making an http request to the server which returns a 401. When buffered, the user is logged out again immediately he logins in. Warm regards

**Comment by witoldsz** [comment]
How is that different from ´ignoreAuthModule´ option? Can you show me a commit, or better, create a pull request, so I can see the change?

**Comment by witoldsz** [comment]
Continued as pull request https://github.com/witoldsz/angular-http-auth/pull/98
